name: deploy
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: amondnet/vercel-action@v20
        id: preview
        if: github.event_name == 'pull_request'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: amondnet/vercel-action@v20
        id: production
        if: github.event_name == 'push'
        with:
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
